### PR TITLE
update to php7+ v2

### PR DESCRIPTION
**Pull request by voku**
[+]: "Parser" -> ~ 50% better parse performance
[+]: use php7 parameter type hints
[*]: add ".travis.yml" -> https://travis-ci.com (https://codecov.io | https://coveralls.io | https://scrutinizer-ci.com)
[*]: add ".editorconfig" -> same base config in vim, PhpStorm, ...
[*]: add ".gitattributes" -> exclude some files, if you install the package via composer

### CODE REVIEW

**Comment by sabas** [comment]
Wow, the performance increase is due to the type hinting or something else?
Let me know if it's complete for merging...

**Comment by voku** [comment]
Noop the performance improvements comes more from reducing function & regex calls and by using strpos (https://stackoverflow.com/a/29728934/1155858) ... 

e.g.: 

from:
```php
 \strrev(
     \preg_replace(
         self::$DELIMITER . $this->symbEnd . self::$DELIMITER,
         "",
         \strrev($str),
         1
     )
 )        
```

to:
```php
 if (\strpos($str, $this->symbEnd) !== false) {
     $str = \preg_replace(
         self::$DELIMITER . $this->symbEnd . '$' . self::$DELIMITER,
         '',
         $str
     );
 }
```

PS: for php 7.0 I think the type hints has a small negative performance effect, but a very small and it's optimized in php >= 7.1

**Comment by voku** [comment]
PS: if you merge this changes, can you also add a new git tag, otherwise my IDE complains about the dev-master in my "composer.json" file, thanks :)

PS2: can you also take a look at https://travis-ci.com/php-edifact/edifact/ and register this package, so that it will be automatically tested with PHP 7.x, thanks again :)

**Comment by sabas** [comment]
For the Travis, I wrote a ticket because I messed up the set up...
I will push a tag asap

**Pull request merged**
