### PR TITLE
Improve UNB Interchange Header recognition for syntax identifier

### PR DESCRIPTION
**Pull request by feyst**
Hi 🙂,

After merging my previous PR I noticed that if the UNA header is present, the UNB recognition doesn't work.
The UNB header recognition and consequently the syntax identifier is not recognized. 

My proposal would be to improve the UNB field recognition.

Let me know if you have any further questions or if I need to make some changes.

### CODE REVIEW

**Comment by sabas** [comment]
Could you please also a wrapped test?
So the same example without newlines...

**Comment by feyst** [comment]
You mean like this right?

**Comment by sabas** [comment]
Yes, I merge it

**Comment by feyst** [comment]
Thanks ❤️

**Comment by sabas** [comment]
Yes, I was doing some additional work on the testing side, I will push today

**Pull request merged**
