### PR TITLE
Add possibility to choose output key (id or name)

### LINKED ISSUE #102: Possibility to have IDs instead of name as output from Interpreter::prepare
Given the fact that the name of fields varies a lot between different versions of the messages it would be beneficial if one could vote to have the result to contain the official IDs instead of the names.

This could be done via an optional configuration of the **_Interpreter_** and would than need some changes at the end of **_Interpeter::processSegment_** from my PoV.

### PR DESCRIPTION
**Pull request by duergner**
Fixes #102

### CODE REVIEW

**Comment by sabas** [comment]
@duergner instead of the constructor, what about making it a flag with a function, like I made in fogglePatching
https://github.com/php-edifact/edifact/blob/master/src/EDI/Interpreter.php#L121

**Comment by duergner** [comment]
Changed it as suggested.

Shall I add the fix for the failing tests as well to this PR (even though it would be unrelated)

**Comment by sabas** [comment]
> Shall I add the fix for the failing tests as well to this PR (even though it would be unrelated)

Yes thank you :)

**Comment by duergner** [comment]
Build should come back to green and I added a test for the new functionality

**Pull request merged**
